[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "configparser>=7.2.0",
    "cors>=1.0.1",
    "fastapi>=0.116.1",
    "openai>=1.101.0",
    "python-multipart>=0.0.20",
    "supabase>=2.18.1",
    "uvicorn>=0.35.0",
]
